### ISSUE TITLE
Handle Selenium StaleElementReferenceException

### ISSUE THREAD

**Issue by d0k1** [d0k1/jsflight#29]
Sometime after an element was found any operation with causes StaleElementReferenceException that breaks the execution flow.
The best option to handle it is to try find element and apply an operation again. 3-5-10 times. Player should give up after 10th StaleElementReferenceException being thrown by webdriver.

**Comment by koldn** [comment]
Outdated, StaleElementReferenceException problem was dealt with here eefd09256f5b22874b49d282b736642e21081569

**Comment by d0k1** [comment]
it's great, thanks!
