### ISSUE TITLE
Record cursor position in text area

### ISSUE THREAD

**Issue by koldn** [d0k1/jsflight#30]
Sometimes user is working with filled text area, setting cursor position by mouse, rather than arrow keys. Cursor position is required for correct dealing with playing keyboard

**Comment by d0k1** [comment]
Thank you.
 jsflight will get this (http://stackoverflow.com/questions/4928586/get-caret-position-in-html-input) eventually

**Comment by gallyamb** [comment]
Fixed

**Comment by d0k1** [comment]
thanks!
