### ISSUE TITLE
Set the lowest possible priority to background firefox

### ISSUE THREAD

**Issue by d0k1** [d0k1/jsflight#37]
I  propose to set the lowest possible priority (at OS Level) to an background  browser instance to leave more CPU or other resources for current browser instance

**Comment by gallyamb** [comment]
If this issue still relevant, I'm possibly found a solution. I think, that we should take a look at `nice|renice` command-line utility. It allow to start new process with (change existing one's) priority.

**Comment by d0k1** [comment]
Actually, this issue is outdated. Jsflight use groovy script to up and down priority of browser instance at the moment.
Btw, nice/renice is a good solution, but it is limited to linux. Groovy script seems like more os-independent way to manage priorities
