### ISSUE TITLE
wrong event type for IE<=8 

### ISSUE THREAD

**Issue by d0k1** [d0k1/jsflight#40]
recorder.js and some other js-files has a condition to select appropriate mechanism to add an event handler
for example
`
if (document.addEventListener) {
        document.addEventListener('click', jsflight.TrackMouse);
    } else {
        document.attachEvent('click', jsflight.TrackMouse);
}
`
The condition above has an error if browser has no document.addEventListener then it should attachEvent **'onclick'**

**Comment by gallyamb** [comment]
Fixed

**Comment by d0k1** [comment]
thanks!
