### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gallyamb** [d0k1/jsflight#46]
App have a memory leak. After playing some amount of steps, it crashes with OutOfMemoryException. Eclipse MAT in memory leak report said, that it might be a org.apache.jmeter.protocol.http.sampler.HTTPSampleResult.
#49

**Comment by gallyamb** [comment]
[Here](http://dropmefiles.com/XbXu0) you can find MAT memory leak report

**Comment by gallyamb** [comment]
[Here](http://dropmefiles.com/XbXu0) another report: top consumers

**Comment by d0k1** [comment]
need to see full heap dump.

**Comment by d0k1** [comment]
Issue fied with https://github.com/d0k1/jsflight/pull/49
