### ISSUE TITLE
SeleniumDriver refactoring

### ISSUE THREAD

**Issue by gallyamb** [d0k1/jsflight#83]
IMO, `SeleniumDriver` class is too complicated, violates "Single responsibility" principle, and therefore, need to be refactored.
For now, `SeleniumDriver`'s responsibility areas is following:
 * manages `WebDriver`s
 * manipulates with `WebElement`s
 * handles all event types
 * manipulates with frames

**Comment by d0k1** [comment]
You are welcome to make a proposal about SeleniumDriver's decomposition to get a better design.
